### ISSUE TITLE
Pie Chart Percentage Data Is Wrong

### ISSUE THREAD

**Issue by danielspizza** [mtotschnig/MyExpenses#1035]
First time ever writing one of these. 
I entered a simple set of figures to see how the app works. The percentages should be an even 50%/50% on the piechart but they are showing as 33.3%/66.7%.
I have tried several variations but the calculations always seem to be off. 
Thankyou.

![Screenshot_20220926-170327](https://user-images.githubusercontent.com/114388083/192221926-2a9c9c75-0876-49a8-8f4c-51cbdf058cdd.png)

**Comment by mtotschnig** [comment]
Would you mind also sharing the list of transactions that generates this distribution?

**Comment by danielspizza** [comment]
![Screenshot_20220926-173507](https://user-images.githubusercontent.com/114388083/192225237-abba21c5-9965-4ad4-af26-77924de0824a.png)

**Comment by danielspizza** [comment]
Sorry mate. I did a couple more numbers..  I think I see what it's doing.

In the piechart It's adding both numbers though one is negative..  then calculating the percentage?

**Comment by mtotschnig** [comment]
In the menu there is the option "Aggregate expenses and income". If you uncheck it, you can see the distribution for income and expenses separately.

**Comment by danielspizza** [comment]
Yes I saw that. But aggregating it should show income percentage and expense percentage ie. EXPENSES X%
INCOME X%

**Comment by danielspizza** [comment]
Like if my business made $1000
And I had expenses of $400... I would know I made 60% profit, or my expenses were 40% of my income.

**Comment by danielspizza** [comment]
Did a little more playing with tthe numbers mate.
It is definitely adding INCOME (1000) + EXPENSE (400) then calculating  percentage of 1400 instead of 1000.

400 / 1000% = 40%  CORRECT ANSWER
400 / 1400% = 28.6% 

Sorry mate. Felt I wasn't explaining myself well enough. 

Thankyou again.
 Have to say the app in general really impressed me. Other than a couple of games... This is the first app I've ever felt was worth paying for so was happy to do so.
Keep it up mate. Cheers :)


![Screenshot_20220926-231356](https://user-images.githubusercontent.com/114388083/192294018-e4426890-1b59-4300-ac9e-422c8fd467f6.png)

**Comment by mtotschnig** [comment]
I understand that the behaviour of the app in this example is counter-intuitive, and should be improved. But your suggestion that the correct answer is 40% is not consistent with what the Distribution screen is supposed to calculate. Its idea is to deal with expenses or income, and to show with respect to the total of your expenses (or income) how many you spend (or earn) per category. The reason why the option to aggregate expenses with income exist, is that you should be able to add transactions that reduce the total for a certain category, for example if you register partial or total reimbursements.
So I think, in order to provide a better experience, the following would need to be changed: 

- Categories would need to be typed as income or expense (#212)

- There should be a toggle between expense/Income independent of the Aggregate switch, so that the distribution would take into account either expense or income categories.

**Comment by mtotschnig** [comment]
Starting with version 3.6.7, the pie chart will no longer will separate income from expense data, so it should no longer be able to generate these confusing results.
