### ISSUE TITLE
Hidden pricing

### ISSUE THREAD

**Issue by Antiwhore** [mtotschnig/MyExpenses#1103]
Hello!
I've recently looked through the site and saw that the program has paid features. What I also wanted to see is the prices of these features - and I didn't! Hence the question - why are you hiding them? Do you consider the prices a big secret or are you ashamed of their size?

**Comment by mtotschnig** [comment]
There is nothing to be ashamed of. Users regularly confirm that compared to other apps, they get excellent value for them. The reason is simple: Prices differ between app stores and markets, due to localised pricing applied where possible (Play Store) and app stores' and payment processors' commissions. The prices are shown in the app on every purchase screen.

**Comment by Antiwhore** [comment]
So the prices in F-droid version will be different from those in Play Market version, is this correct?

**Comment by mtotschnig** [comment]
If you live in the US or central/western/northern Europe, there won't be a big difference. For other markets, PlayStore has localiced (cheaper) prices, which is not possible to do on F-Droid since information about user's country of residences is not available.

**Comment by Antiwhore** [comment]
I see, that's interesting. Then could you write about it on the premium page (like "see the prices in the app itself")? Absenсe of prices looks odd.
