### ISSUE TITLE
Data loss

### ISSUE THREAD

**Issue by Cerdtruir** [mtotschnig/MyExpenses#1125]
Hi

My app updated and I lost all my data

Is there any way to get it back. I see it's a known issue but I don't see any info on it

**Comment by mtotschnig** [comment]
Unfortunately version 3.5.0 (580), distributed for a short time on Google Play, had a major flaw that did lead to data loss on devices with Android 10 and earlier.
The reason was that due to a debug statement that got accidentally committed into production, the device opened the database with the native sqlite, whereas since version 3.4.6, we use a bundled more recent version of sqlite. Since the native sqlite was not able to open the database, it reported corruption, and code in SupportSQLiteOpenHelper (that I was not aware of) from the Androidx Sqlite library then decided to delete the file. 
I have reported this as dangerous to Google: https://issuetracker.google.com/issues/267355686, but it is still entirely my fault and I apologize to all affected users, that are not able to recover the data from a recent backup.
One resolution strategy was reported as successful by some users: If you have opted into device backup to Google Drive during setup of the device, you might be able to restore the data from there by uninstalling and reinstalling the app.
Please contact support@myexpenses.mobi for further questions.
