### ISSUE TITLE
Implement case insensitive search for non-ascii letters

### ISSUE THREAD

**Issue by kovdan01** [mtotschnig/MyExpenses#1140]
Currently, when searching for notes containing specific text in Cyrillic alphabet, the search is performed in a case sensitive manner. For Latin letters, case-insensitive search works properly. It would be nice to implement the same behavior for some wide-spread non-Latin alphabets, since case-sensitive search is unhandy in 99% of use cases.

**Comment by mtotschnig** [comment]
Thanks for bringing this up. Actually the limitation not only concerns non-latin characters, but also non-ascii characters, i.e. any latin character with diacritics, like German öäü, French áéè etc.

**Comment by mtotschnig** [comment]
The problem is that since version 3.4.6, the project has made a choice that I start to regret: I switched the project to using requery, which allows to use a more modern sqlite version than the one that Android makes available as part of the OS. The rationale was to make use of new features like JSON support and windowing functions on all API levels. Unfortunately I understood too late, that requery does not have the same internationalization support baked in that the sqlite from the Android framework has. So I am considering now to move away from requery, but it is not trivial, because the database that requery's sqlite is maintaining now cannot be read with the framework sqlite, so a careful migration is needed, and the threat of data loss (as happened in #1125) is present again.

**Comment by mtotschnig** [comment]
@kovdan01 If you have a spare Android device where you can test out the last version that still used the native sqlite from here: https://apt.izzysoft.de/fdroid/index/apk/org.totschnig.myexpenses?repo=archive (version 3.4.5.2), it would be very helpful for me to learn if with this version case insensitive search works correctly with Cyrrilc letters.

**Comment by kovdan01** [comment]
@mtotschnig Tried 3.4.5.2 - case insensitive search works properly for Cyrillic letters. So, migrating to framework sqlite should do the trick. Thanks!
