### ISSUE TITLE
Applying scheduled transaction sets incorrect date

### ISSUE THREAD

**Issue by sivaraam** [mtotschnig/MyExpenses#1229]
I have some scheduled transactions. When applying the transactions directly voa the notification, the date and time associated with them is incorrect (01-Jan 1970, seems like the epoch).

I'm using v3.6.0 of the app on a OnePlus Nord running Android 12.

**Comment by mtotschnig** [comment]
@sivaraam Interestingly, it seems that this bug has existed since #530 was implemented. For me it only happens if "Time for manually applied scheduled transaction" is set to "Time of application" and if on the Notification you click on "Apply". Is it possible that you until now you always used the "Edit" button?

**Comment by sivaraam** [comment]
> Is it possible that until now you always used the "Edit" button?

Indeed. I actually just tried using the "Apply" menu 😅
