### ISSUE TITLE
Problem with initialising FinTS and comdirect

### ISSUE THREAD

**Issue by kahllenny** [mtotschnig/MyExpenses#1332]
I always get error while fetching UPD
It also opens a PhotoTan box behind the login so i can only acess it once i cancled the login
I am on Android 14 and want to use FinTS with Comdirect

**Comment by mtotschnig** [comment]
@kahllenny Thank you for the report. I suggest to not post the log of the Banking feature here, since it might contain privacy sensitive information. Would it be possible for you to document the behavior of the app with screenshots and/or screen recording. You could either post them here, or maybe preferably communicate directly with me via support@myexpenses.mobi.
