### ISSUE TITLE
[Android] Remove local calendar provider

### ISSUE THREAD

**Issue by marcelmindemann** [mtotschnig/MyExpenses#1338]
Hello,
I have used MyExpenses in the past, it was a great app and I have been very happy with it. However, I grew out of it and have uninstalled it from my phone. However, the local calendar "MyExpenses planner" is sticking around on my phone. Is there a way to remove the local calendar using the app?

**Comment by mtotschnig** [comment]
Thanks for bringing this up. I used to recommend Offline Calendar (https://f-droid.org/en/packages/org.sufficientlysecure.localcalendar/) which allows to delete local calendars. It is not longer maintained, and the same functionality is part of its successor Etar https://f-droid.org/packages/ws.xsoh.etar/, which is a full-blown calendar app. But you are right, that My Expenses should offer the user to remove the local calendar it creates. Will add this to upcoming version.

**Comment by mtotschnig** [comment]
Removal of the local calendar is now possible in version 3.7.0 (Settings, chapter Advanced). but there is a caveat:
If you have uninstalled the app and now just install it again in order to remove the calendar, the app does not have the calendar permission and is not able to find out if the local calendar is set up. But I do not want to show the option to all users indiscriminately. So in order to make the option appear you would either need to grant the Calendar permission via Android's system settings, or click on the Calendar entry in the Planner section which prompts for granting the permission.
