### ISSUE TITLE
How do I compile with premium features pre-activated?

### ISSUE THREAD

**Issue by myclevorname** [mtotschnig/MyExpenses#1362]
I like the program, but I don't think it is worth my money to pay for a subscription. This is definitely a stupid question, but how do I compile this program with the Professional Key features activated by default?

This isn't a monetary issue. I can afford this and I have paid money for other proprietary software. This is a moral issue for me. I feel a conflict between the nature of open source and the subscription model in this piece of software. I understand that the maintainer wants to make money, but I chose to try this software not necessarily because it was better, but because it was *free* and open source.
<\/rant>

Being able to compile with the premium features enabled could also help developers debug premium features without forcing them to contribute money just to contribute time.

**Comment by mtotschnig** [comment]
My Expenses is **free** software (as in free speech): https://www.gnu.org/philosophy/free-sw.en.html
You are **free** to modify method isEnabledFor(licenceStatus: LicenceStatus) in file LicenceHandler.kt and build it with all functionality enabled.
I decided to package some features as not _free_ (as in free beer) in order to build a business on top of this project, which allows me to dedicate time to it. Without this business model, My Expenses would probably only have around 25% of its current functionality. All functionality can be purchased as one-time purchases. There is not need to go with the subscription. By (regularly) supporting this project, you can contribute to help this project grow in functionality for another 10 years instead of being abandoned.

**Comment by teoc98** [comment]
> All functionality can be purchased as one-time purchases. There is not need to go with the subscription. 

As far as what is presented by the app as contribution options, this is not true since at the moment
- unlimited number of splits
- history chart
- budgeting
- scan receipt
- web user interface
- category tree

are available only with a _professional key_, which is not a one-time payment. 

Personally, I'm not willing to pay a subscription for "offline" features, i.e. those that I would get by modifying the source code and recompiling. Is there any chance to have a one-time payment key which grants everything that the professional key does, except for "email support with guaranteed response within 2 business day" and "voting right on development roadmap"? Thank you anyway. 

-----

I'm aware of the difficulties of a business model for FOSS, and I thank you and all contributors for your work, which in practice is free both as in free speech and as in free beer, since the code of the features packaged as not _free_ (as in free beer) is still accessible on GitHub for _free_ (as in free beer).

**Comment by mtotschnig** [comment]
@teoc98 Whenever you call one of the features you mention, the option to purchase the feature individually is not visible right a way, you need to scroll down to see it.
![Screenshot_1712309484](https://github.com/mtotschnig/MyExpenses/assets/1485456/5df9f7ae-c09f-4092-99ab-ec6ed3e5d70d)
You can contact support@myexpenses.mobi and I can prepare an invoice with multiple features for a single payment via bank transfer.
