### ISSUE TITLE
SQLite error when transferring from one account to another

### ISSUE THREAD

**Issue by PBoy68** [mtotschnig/MyExpenses#1431]
Every time I transfer money from one account to another, I get the following error message when I press the validation button. If I try again, it works fine.

![Screenshot_2024-02-26-16-36-34-29_30ebfaaae7046286c358d6571efbd74b](https://github.com/mtotschnig/MyExpenses/assets/141337151/7598447b-1c7f-49a0-8b1a-f49838ecefc2)

**Comment by mtotschnig** [comment]
@PBoy68 Thanks a lot for the report. Very likely, the reason is that you accidentally deleted the default transfer category. Could you open the Advanced chapter in the Settings, and select "Default transfer category", and either select a category or "Unmapped". When you delete a single category, the app already has a check if it is configured as default transfer category, but this check is currently missing during bulk delete. I will fix this for the next version.

**Comment by PBoy68** [comment]
That's it! I don't know how it happened but if I redefine a transfer default category in the settings, the problem no longer exists. Thanks for the feedback.
