### ISSUE TITLE
Web interface is unavailable when using hotspot or tethering

### ISSUE THREAD

**Issue by aerfanr** [mtotschnig/MyExpenses#1543]
The app does not allow activating the web user interface when not connected to a wifi network. But users should logically be able to use the web interface over mobile hotspot, or USB or Bluetooth tethering.

Potential fix:
This code from `myExpenses/src/main/java/org/totschnig/myexpenses/util/io/NetworkUtils.kt` is used to check for wifi connection:
```kt
fun isConnectedWifi(context: Context) = getConnectionType(context) == 2

@IntRange(from = 0, to = 3)
fun getConnectionType(context: Context) =
    // Returns connection type. 0: none; 1: mobile data; 2: wifi; 3: vpn
    (context.getSystemService(Context.CONNECTIVITY_SERVICE) as? ConnectivityManager)?.let {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M)
            getConnectionType23(it)
        else
            getConnectionTypeLegacy(it)
    } ?: 0

@RequiresApi(Build.VERSION_CODES.M)
private fun getConnectionType23(cm: ConnectivityManager): Int =
    cm.getNetworkCapabilities(cm.activeNetwork)?.run {
        when {
            hasTransport(NetworkCapabilities.TRANSPORT_WIFI) -> 2
            hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR) -> 1
            hasTransport(NetworkCapabilities.TRANSPORT_VPN) -> 3
            else -> 0
        }
    } ?: 0
```

From my understanding, it would fix the problem if instead of checking for only `TRANSPORT_WIFI` it checked for either `TRANSPORT_WIFI` or `NET_CAPABILITY_LOCAL_NETWORK`. See [https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_LOCAL_NETWORK](https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_LOCAL_NETWORK)

Unfortunately I cannot test if this works as I am not an Android developer and therefore do not have the required tooling installed to compile the software.

**Comment by mtotschnig** [comment]
@aerfanr Thanks a lot for bringing this up. I am still trying to figure out how to make use NET_CAPABILITY_LOCAL_NETWORK. It is not as easy as just adding a check for NET_CAPABILITY_LOCAL_NETWORK, because the hotspot is not returned via cm.activeNetwork. If I find out how to make use of it, it would still be limited to Android 15 devices or Android 14 with a certain extension level.
But on my way, I realized, that My Expenses could request the OS itself to open a hotspot and then it should be easy to bind the web user interface server to that network. What do you think of this idea?

**Comment by aerfanr** [comment]
Well so NET_CAPABILITY_LOCAL_NETWORK wouldn't work.
Starting a hotspot sounds good. But the app should ask the user first before starting the hotspot automatically, because a user might want to run the web UI and use it over USB or Bluetooth tethering or maybe on a browser on the same device (don't know why they would, but they should be able to do so)

Overall I think there should be no restriction on when to start the web UI, rather a suggestion to connect to or create a network.

**Comment by mtotschnig** [comment]
I have taken a deeper look into this. On the one hand, Android just does not allow you to bind to an existing hotspot. There is a bug report on this https://issuetracker.google.com/issues/200974389, where Google on the one hand recognized it as a problem, but on the other hand closed as wont-fix.
On the other hand, I am not sure how useful a local only hotspot would be. It would require you to connect your PC to this local hotspot, and I guess that if your PC does not have any additional network interfaces, you would not have any Internet access, while connecting with MyExpenses Web User Interface. Is this something users would really use? I have the impression, this is too narrow a use case to warrant further effort, but I will keep this open for others to comment. I can also add it to the roadmap vote upon request.

**Comment by aerfanr** [comment]
I apparently do not understand something here. What does it mean to "bind to an existing hotspot"?

I could open Termux on my phone, start my hotspot, and run a command like `python -m http.server` in termux to launch a webserver, then access that server from my laptop wich is connected to my mobile hotspot, having internet access through the same hotspot at the same time. How is this different for MyExpenses. Does MyExpenses do something different than just launching an http server?

**Comment by mtotschnig** [comment]
You are right that the expression "bind to an existing hotspot" is mistaken. The http server that MyExpenses launches is actually not bound to a single interface, but to all interfaces, hence it might work on the hotspot. What I was actually trying to find out was how the app could detect the existence of the hotspot, and then display the server address that would allow to reach the server via the hotspot, and that seems to be difficult. But if the user already knows the ip address of the hotspot (which he should be able to find out by inspecting the network information on the connected device, since the hotspot is identical with the gateway address provided via dhcp), he should be able to connect to the web ui. I will give this a try and report the result. I am just unsure if the user experience would be acceptable of essentially telling the user "I am running a service here, but you need to find out yourself how to contact me".

**Comment by mtotschnig** [comment]
I have implemented the option to start Web User Interface when device is not connected to WiFi. 
User is prompted to confirm:
![Screenshot_20240808_235449](https://github.com/user-attachments/assets/76020099-fe4b-4e2d-b0d1-7d5ce9793847)
And only info on port is given once server is started:
![grafik](https://github.com/user-attachments/assets/aebfd7c7-b8fe-4ecf-9fd0-3d8fa2b3572e)
There is a method that allows to enumerate all network interfaces, so it would be technically possible, to display them to the user, but I am not sure how to filter out ALL irrelevant interfaces.
