### ISSUE TITLE
Google marks this app as unsafe

### ISSUE THREAD

**Issue by reachvineetjain** [mtotschnig/MyExpenses#1574]
![Screenshot_20241012_152118_Google Play Store.jpg](https://github.com/user-attachments/assets/17c1a28c-1d7d-43a5-9051-692e9cfc7c7a)

**Comment by mtotschnig** [comment]
This screenshot does not represent this app (My Expenses), but a separate companion app (My Expenses Contrib Key) that was used until 2017 for the purchase of license keys, which are now sold via in-app purchases. Until now it is still possible to active the key bought by this old mechanism, but you can also contact support@myexpenses.mobi with a confirmation of your purchase and I will send you an alternative code so that you do not need the "My Expenses Contrib Key" app any more.
