### ISSUE TITLE
Transaction edit form: Comment field does not grow with content any more

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#1596]
In 3.9.0.1, by trying to increase minimum touch target size of the comment field, we accidentally limited its height, so that it does not grow any more with multi-line content.

**Comment by ItsIgnacioPortal** [comment]
This issue is still present in v4.0.4.2 🤔

Only the first line is shown in the notes of transactions with multi-line comments.

The transaction in the editor:
![Screenshot_20251029-075942.png](https://github.com/user-attachments/assets/965dd5d8-5396-4389-a904-04e05ba40f45)

Vs how it looks in the transactions list:
![Screenshot_20251029-075947.png](https://github.com/user-attachments/assets/b214f9ec-4880-4712-8639-6a6ed5cda462)
