### ISSUE TITLE
OneDrive backup issue

### ISSUE THREAD

**Issue by chidi9901** [mtotschnig/MyExpenses#1597]
I don't know what has happened, but from around last week, there is an issue writing the backup file to OneDrive. A notification appears stating that there is an error writing the file. The actual error message is only: Error while executing the request. When I check on OneDrive, nothing is written or uploaded there. But the backup file is indeed created on my phone.

I am using the app on my S24 Ultra with Android 14.

Backend syncing on the other hand still works without issues.

**Comment by mtotschnig** [comment]
Thank you for the report. Is it possible that the size of your backup file increased significantly lately? I have the suspicion that OneDrive becomes unhappy with larger files. In order to help me analyze further, you could do one or both of the following:
1) Activate debug logging and share the result as described here: 
https://github.com/mtotschnig/MyExpenses/wiki/FAQ:-Synchronization#synchronization-stopped-working-how-can-i-find-out-why
2) If you are on the Play Store version, share the Crashlytics UserId with support@myexpenses.mobi. You can find it in the Settings -> Advanced (section Debug). Long tapping allows to copy to clipboard.

**Comment by chidi9901** [comment]
If it's caused by the size, I have zero idea, one backup file is about 21.47MB now.

Here are the the logs.

[SyncAdapter-latest.log](https://github.com/user-attachments/files/17789663/SyncAdapter-latest.log)
[TransactionProvider-latest.log](https://github.com/user-attachments/files/17789664/TransactionProvider-latest.log)

**Comment by mtotschnig** [comment]
@chidi9901 Thanks a lot for the info. I was able to reproduce the issue, and find an explanation (https://github.com/microsoftgraph/msgraph-sdk-java/issues/2026). I am researching if an upgrade of the Microsoft Graph library will fix the issue, and if possible, publish a version with this fix shortly.
