### ISSUE TITLE
highlight if account balance is positive or negative

### ISSUE THREAD

**Issue by ilf** [mtotschnig/MyExpenses#269]
Currently, the total balance on top of each account view doesn't make it clear if it's positive or negative. This is verry irritating.

How about adding a "+"/"-" in front and/or coloring it green/red?

**Comment by mtotschnig** [comment]
It probably is a good idea to color it green/red since this is used for the individual transaction amounts as well. But the amount itself already is formatted as positive/negative number according to the rule of the locale, in German this means having + or - in front, in some other languages negative numbers are put in parantheses.
