### ISSUE TITLE
Introduce FAB sub-buttons

### ISSUE THREAD

**Issue by keunes** [mtotschnig/MyExpenses#300]
If one often creates different items (transaction, split or transfer) it's annoying to every Tims have to use the dropdown menu to change the type. It would be easier to just select the correct type before opening the view.
This could be done by adding sub-FABs as done by the Dutch national railways (app: NS Reisplanner Xtra), and as attached in the screenshot. Works very nice IMHO; one tap opens the list of subFABs, another tap closes it again. Even 'new template' could be added this way (though that can easily be omitted).

I can also imagine it being introduced as a setting (FAB: either of the three options, or sth along the lines of 'show subFAB')

![tmp_11217-screenshot_2016-05-31-00-32-01-011017545477](https://cloud.githubusercontent.com/assets/11229646/15659259/49ff18b8-26c8-11e6-81d9-261bbde81caf.jpeg)

**Comment by mtotschnig** [comment]
Thank you for bringing this app. I had evaluated this approach, back when I implemented the new design, and had decided against it, because I wanted to stick with the idea that the most common type of operation should be available with a minimum of interactions (normal transactions), and that it would be acceptable that the less commonly used ones (transfers and splits) needed two additional steps. In the mean time I learnt that the current solution suffers from the discoverability problem, so I will reconsider the approach based on your suggestion of providing options.

**Comment by sivaraam** [comment]
I guess you could make long pressing FAB to trigger the default action. This way tapping the FAB shows sub-menus and long pressing could trigger 'New transaction' without two taps. FWIW, I consider long pressing easier than two taps :-)

**Comment by sabi0** [comment]
Transaction group summary shows incomes, expenses and transfers total as "equally ranked".
And it is non-intuitive that adding a new record favors the former two more.

I would prefer the FAB to have 4 options:
- Split (yellow?)
- Transfer (blue?)
- Income (green)
- Expense (red)

Alternatively the transaction type toggle on the "New" screen could have 3 options instead of two: Expense - Income - Transfer.

**Comment by mtotschnig** [comment]
My plan is to leave the default behaviour of the FAB unchanged and open a simple popup menu on long press.
![device-2020-10-25-183701](https://user-images.githubusercontent.com/1485456/97114499-26464180-16f1-11eb-8abf-2a3df09e8da9.png)

@sivaraam , @sabi0  , @keunes Any thoughts?

**Comment by sivaraam** [comment]
Rather than a simple pop-up, it would be nice if it is accompanied by icons as they would be helpful alongside text.

**Comment by mtotschnig** [comment]
@sivaraam Thank you for the suggestion. Adopted:
![Bildschirmfoto 2020-10-26 um 23 49 30](https://user-images.githubusercontent.com/1485456/97236749-0e041e80-17e6-11eb-8782-6fb73de61d89.png)
