### ISSUE TITLE
Introduce 'Close account'

### ISSUE THREAD

**Issue by keunes** [mtotschnig/MyExpenses#303]
I just closed a bank account. Current balance has been transferred to another account before closing. I would like to 'close' the account in MyExpenses as well, but also keep all transaction information so that it can be taken taken into consideration for all statistics etc of the past year, payees, etc.

So I would like to propose this as a new feature:
'Closing' an account, which will:
- keep all transaction data in the database (& all data will be considered in all functionalities)
- remove (not display) the account from the NavDrawer
- 'lock' all transactions/transfers (disable editing, in case they might be accessed via some overview, e.g. if #292 / #241 or #222 gets implemented)
- add a new setting "Manage closed accounts" (which opens a dialog to re-open the accounts or delete them)

**Comment by trmendes** [comment]
Very useful feature. I have been traveling and to keep in track with all the expenses I open an account for each country I visit and when I leave the country to the next one the account still there active.

**Comment by akosiaris** [comment]
I would find this feature useful too, for pretty much similar reasons

**Comment by mtotschnig** [comment]
@keunes There is one piece missing from your specification. I suppose that it you still want to inspect the closed account, i.e it should be possible to list its data in the same way as an open account. That is why I suggest to distinguish between two states: Open/Closed and Shown/Hidden. Then, a hidden account could still be considered open, i.e. it could still be updated via Synchronization/Import or Editing of Transfers from the transfer account. What do you think?

**Comment by Akito13** [comment]
> 
> 
> @keunes There is one piece missing from your specification. I suppose that you still want to inspect the closed account, i.e it should be possible to list its data in the same way as an open account. That is why I suggest to distinguish between two states: Open/Closed and Shown/Hidden. Then, a hidden account could still be configured as open, i.e. it could still be updated via Synchronization/Import or Editing of Transfers from the transfer account. What do you think?

I'll take the liberty to chime in on this topic. 
Just for clarification: do you mean that one should be able to hide normal open accounts that are, e.g. only rarely used, so you don't have to see them all the time or would you like to apply this show/hide property only to closed accounts?

> Then, a hidden account could still be configured as open

I'm asking because of this, since I don't know if you meant it literally.

**Comment by Akito13** [comment]
> 
> 
> @Akito13 Yes, that is what I meant: Both open and closed accounts could be either shown or hidden.

I think this is a good idea, because this expands the customizability and flexibility of management operations. 
I would probably use the "Hide" function for accounts that I use very rarely, nonetheless, I am still using them, so I can't close them. In my opinion, you should definitely implement this feature.
