### ISSUE TITLE
Synchronize account metadata

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#343]
Currently, account metadata is only written/read from/to backend upon setup. Changes to an account should be synced. Also exclude_from_totals should be included into metadata

**Comment by OskarSchoenherr** [comment]
This feature would be very important, 

I thank. currently I use MyExpenses mostly for input my expenses during my private or business trips or on holidays. I export the data, use a private transformation app I wrote and import the data into my private finance program (Finanzmanager by Lexware). With this program I also online banking.  That's why I have different opening balances (or endbalances) in  both solutions. With sync the opening balance I would be able, to manipulate this data automaticly with datas I can exporte from my Finanzmanager

The second problem ist the use of to mobile phones. Yes, I can make a synchronization. But if I change the opening balance on one device, it doesn't change on the other.
