### ISSUE TITLE
Reconsider 3-step premium options

### ISSUE THREAD

**Issue by keunes** [mtotschnig/MyExpenses#433]
Though I cannot remember what came first (the extended key or the automated back-up) I do remember I was rather (negatively) surprised when automated backup was not included in the app purchase (the contrib key). To me it's such a basic functionality that it's weird that it's not included in the cheapest premium option. I've been thinking about it a long time whether to share this or not, but I'd now like to suggest to reconsider the premium options.

I can imagine it being difficult to shuffle options around, esp with existing consumers. But I personally would rather see automated back-up then PDF export as contrib feature, as (IMHO) back-up is more essential/basic than a print-out of all expenses.

I'm curious to hear what @mtotschnig and other users think about this.
EDIT: I published this as I was reading about the conversion and advanced backup functionalities and wondering in which premium category that might end up.

**Comment by mtotschnig** [comment]
Thanks for your interesting thoughts. It it true that the way how the options are grouped has not been motivated by a distinction between essential and non-essential features, but by the historical introduction of more expensive packages in the process of My Expenses becoming more feature rich, and the project of creating a business model for its sustainable development. 
Both sales on F-Droid and Play, have properties that make it extremely difficult to achieve this with prices in the range of very few $ or €. On F-Droid, with the overhead of maintaining the purchase process, on Play with the important cut of 30% that Google takes. That is why I am trying to position My Expenses as a professional project with professional services where users evaluate its worth a bit more than these very low prices. So the Contrib package is used as a teaser for users that would be drawn off at first sight by the price of the Extended package.
It might make sense also from an economical/marketing point of view, to switch Printing and Auto-Backup, but as you mentioned, it would come with a considerable development effort, because existing users would need to keep the privileges they have paid for.
I am not completely sure what you mean by the "conversion and advances backup functionalities"? But generally speaking my objective with My Expenses is to implement a business model allowing me to dedicate resources for advanced use cases.

**Comment by funnym0nk3y** [comment]
I like to add to this discussion the option of reconsidering not only the grouping of features, but also the premium options in general. For example, if I am paying regularly for the Pro option, which is afaik 8,95€ a year, I am paying each year more than the next lower key, which is fine. But if don't need the support option any more, and decide to discontinue paying for the Pro version I am left with the very basic functionality. Besides that, the options Contrib and extended feel kind of incomplete to me: You get the template widget, but split transactions are excluded. I would suggest (as a user with no insight to the projects finances) to group the features different: Make Contrib and Extended key feature only options, with the ability to get all features (and upcoming) with a one time payment. And then make the Pro Key a support & vote option with repeating fees as addon to the feature keys.

**Comment by mtotschnig** [comment]
Thank you for your thoughts. As mentioned, the subscription model for the professional licence was introduced as a business model for sustainable development. According to my experience, this can not be achieved by one-time payments which grant users unlimited free upgrade to a constantly improved product. I share your thought, that the Professional licence should include unlimited access to Extended feature, and actually this, although not documented, is the case with the key management implemented for the F-Droid version (for keys that were active during a minimum duration of 1 year). I'll add this information both to the website and the app. For Play, I'd like to provide the same, but if possible at all, it would need considerable effort, since the play licensing library does not inform about expired licences. Thus that fallback could not be activated on devices where My Expenses is installed after the subscription has been cancelled.

**Comment by mtotschnig** [comment]
@funnym0nk3y Both template widget and split transactions are included in the Contrib key.

**Comment by funnym0nk3y** [comment]
@mtotschnig Yeah, I was refering to the point of "Unlimited templates for split transactions" (if the translation from my german app is kind of right). What I wrote was misleading. If I buy the Contrib or Extended key, I get the widget for templates (including split templates). But the number of split templates I can use is limited, right? At least that's what I gathered from the screen where I can select different options and what made the option feel incomplete. 
Anyway, I completely undestand the need for a sustainable business model. It was a little difficult for me to understand how it works, so maybe it would be good to simplify and clarify the options?

Thank's for your work!

**Comment by edo0** [comment]
Dear @mtotschnig
 
While I consider myself a great fan of your app (on board since 3 years, happily paying user), of its rich functionality and easiness of use, I would like to express my views on why I do not agree with the way the subscription model for the Professional Key is currently implemented.

While I am more than supportive of a business model that proves more sustainable for you, I find the current model being penalising especially towards long term supporters and fans, people who are most likely to spread the word and recommend your app to their close ones, and now faced with the prospect of being stuck with a subscription-based system which makes distinctions between services and functionalities blurry (I personally deem services like online back-up and fast support righteously subscription-based [perpetuous cost of server and human customer care], but disagree with crippling the app functionality by putting Budgeting and possibly new future functionalities exclusively in the Professional key: doing so delegitimizes the "Extended" key, the point of which would be to bring around the extra functionalities not part of "Contributor" key.

I agree with your point of one-time payers unfairly enjoying the fruits of all your future developments (even though I won't argue about the importance early adopters might have had either financially or motivationally for you), but as things are now, if anyone subscribed for 1 or 2 years and than ceased, they would conversely end up locked out of the very functionalities they financed.

At this point, a more balanced option that I feel like advising to you, would be adding a "life-time professional subscription" option, that for 20/25/30/60€? will provide access to new features to users seriously committed to a long term relationship with your app.


Lastly, unrelated but close to me, do you think it would be possible to introduce some sort of discounts for students? Budgeting is important for them, and they are known for having little budget to afford that ;)

**Comment by edo0** [comment]
Thank you very much for your answer, I really appreciate it. I see the point of your choice, and even if It's not 100% in line with my views, I do admire your statement of flexibility.

**Comment by sabi0** [comment]
As long as this issue is still open I'd like to add that I like the licensing approach implemented by JetBrains for their IDEs.

A personal license gives user access to all the new features (application releases) developed while the license lasts, without any limitations. (Not "services" though, like priority support)
When the license ends the user can continue using the release on the date of the last license payment for as long as he likes.

This approach has several interesting benefits:
- it "teases" the users with the new features motivating them to extend the license
- it guarantees that a one-time payment is enough to keep the current release functionality available forever

There are some caveats however
- JetBrains IDE license cost is in the EUR 100+ range
- rolling back to the previous Android application version (while retaining the data!) and then keeping it there despite the Android update mechanism is ... challenging. I imagine this could be done with: export from the latest release, uninstalling it, installing a "release when the license was purchased" via special apk to prevent auto-updates, importing the data back. But on the other hand it could be another (strong) reason to pay for the license extension.
- keeping export/import backward compatibility to ensure users could revert to 1-year old release when their license expires might be tricky

**Comment by mtotschnig** [comment]
With 3.2.5, all professional features are now sold as single AddOn Packages, thus a subscription is no longer needed in order to use all features.
