### ISSUE TITLE
Schedule transactions notified at start of day instead of time of transaction

### ISSUE THREAD

**Issue by fantasio31** [mtotschnig/MyExpenses#478]
While scheduled transactions are planned at different hours of the day, notification are always raised at start of the day.

Scheduled transactions are corerctly taken into account at scheduled time.

Maybe it is an incorrect calendar event reminder hour for notification ?

**Comment by mtotschnig** [comment]
This has been changed on purpose for the following reason: My Expenses does not set alarms for each event, but regularly (every six hours) checks for pending events. Previously this led to the situation where plans set for a time towards the end of the day would only trigger the next day. For example if the check runs at 10 pm, the event is set to 11 pm, it would only be triggered on the next run at 4 am the next day. That is why now, we check for all events for the same day.
Since a plan normally is set for day, and not for a time, this seemed to be the more correct behaviour. Is there a special reason why it is important for you, that the notification appears nearer to the time?

**Comment by fantasio31** [comment]
OK for the explanation, but my phone stay on during the night, and notification is raised at night which could wake me up.

It could be great to have the possibility to configure the hour of the reminder in parameters: for example, 8:00 or 12:00.

**Comment by mtotschnig** [comment]
This is a good point. I will investigate if we could change the processing of plans to be run only once and at a user configured time, maybe somewhen in the morning by default.
