### ISSUE TITLE
[feature request] Autodetection with camera

### ISSUE THREAD

**Issue by nr458h** [mtotschnig/MyExpenses#484]
As a german user most bills have a common set of data (like date, amount, cardnumber or cash ...) so in my opinion it would be awesome to have a autodetection through scanning the bill --> and than be able to check all detected data.

I now this is a very big request so if it not fits your idea of the app fell free to close this issue.

Beside: I realy like this app and thanks for making it open source!!

**Comment by funnym0nk3y** [comment]
Well, I'm by far no expert at this, but wouldn't it be possible to use Tesseract in combination with OpenCV to get a text file of the receipt an then perform a few text-based operations to extract the infromation?

**Comment by mtotschnig** [comment]
Due to its position on the top of the roadmap vote, I am looking into to what extent image detection capabilities can be added to My Expenses. From my perspective, only information encoded in barcodes or QR codes is doable with a reasonable amount of effort. Unfortunately in Germany, where I currently live, bills do not carry any barcodes with usable information, contrary to Austria, where this is the case due to legal requirements. If you know of any type bill with interesting bar or QR codes, please add your comments.

**Comment by edo0** [comment]
In Italy there is no standardized usage of barcodes in receipts, and in the great majority  of cases they will not appear.
However, a keyword always found on the line of the grand total, is "TOTALE" (either alone, or followed by "EURO", "EUR", or "€"), and then the amount

(For examples: https://www.google.com/search?q=scontrino+fiscale+italia&prmd=inmv&source=lnms&tbm=isch&sa=X)

**Comment by mtotschnig** [comment]
The current implementation is based on Googles Mlkit and will only be used on the Play Store version. For the F-Droid version I plan to implement a solution based on Tesseract.

**Comment by mtotschnig** [comment]
I was not yet able to look into a solution based on Tesseract. For the moment, the idea is that F-Droid users can install an external APK based on mlkit as explained in the FAQ.
