### ISSUE TITLE
Using scheduled transaction to create an entry should fill time with current time

### ISSUE THREAD

**Issue by sivaraam** [mtotschnig/MyExpenses#530]
When I schedule a transaction for a certain day, the time that gets filled when I edit the transaction (and eventually save it) is the start of the day (12:00 A.M.) rather the time at which I'm editing it. The time that gets filled should be the time at which I'm editing/saving it as that is the time I consider the transaction to be done.

I use version 2.9.6.2 of the app.

Note: Just FYI, this is not a duplicate of #478. It's different.

**Comment by mtotschnig** [comment]
Are you sure that the time is 12:00 A.M? It should be 12:00 P.M (i.e. noon). My Expenses plans currently work with a fixed time. Since there is no input for entering the time, we thought that the exact time would not be relevant for the user either, and relying on a fixed time, makes the handling of the plans more consistent. Thus even if this is different from #478, it is related.
Is there a specific reason why the fixed time is disturbing for you?

**Comment by sivaraam** [comment]
> Are you sure that the time is 12:00 A.M? It should be 12:00 P.M (i.e. noon). 

You're correct. I might have missed something. 

> Is there a specific reason why the fixed time is disturbing for you?

Because I'm one of those outliers who tries to keep track of the exact time of a transaction. So, the fixed tone is disturbing me.

To give you a more clear idea, during the week days I eat outside at some hotel. I have a scheduled plan each for break fast, lunch and dinner. I like to keep track of the time at which I execute the plan. This is one of the cases in which I would like to keep track of the time. I like to keep track of the time otherwise too.

**Comment by mtotschnig** [comment]
Thinking about this again, I am no longer sure about the value of this proposal:
If it is a scheduled transaction, My Expenses will notify at a certain time, that is not related to the specific occurrence of the event. And even if you do not immediately apply the template, often you wont do it at the exact time of the event, but some time later.
In any case keeping track of the time, is perfectly possible already, since you can set the time while editing the transaction.

**Comment by mtotschnig** [comment]
@sivaraam Would your use case also be addressed, if it were possible to store the exact time with the plan, and then the entry would have the same time?

**Comment by sivaraam** [comment]
> @sivaraam Would your use case also be addressed, if it were possible to store the exact time with the plan, and then the entry would have the same time?

Yeah, that would indeed be an improvement over the current situation. Though, it's not a perfect solution because the time varies in some cases. 

Anyways, if I'm the only person around wanting this to happen, feel free to drop it. It just might not be worth it. I can live with editing the transaction time when applying the transaction. After all, I've been doing it all this while 🙂

BTW, is it normal that scheduled manual transactions gets applied automatically after the date of the transaction is passed?

**Comment by mtotschnig** [comment]
@sivaraam I would like to make sure I understand your use case correctly: At the moment, you are notified about these plans at the beginning of the day. Then you keep them open, until the moment, when this transaction effectively takes place. This is when you select the notification in order to apply the plan, and hence would like to see the time be set to the current time. Is this correct?

> BTW, is it normal that scheduled manual transactions gets applied automatically after the date of the transaction is passed?

When you observed this behaviour, was the manual plan still visible as a notification? Or was the phone switched up in the meantime?

**Comment by sivaraam** [comment]
> @sivaraam I would like to make sure I understand your use case correctly: At the moment, you are notified about these plans at the beginning of the day. Then you keep them open, until the moment, when this transaction effectively takes place. This is when you select the notification in order to apply the plan, and hence would like to see the time be set to the current time. Is this correct?
>

Yes, that's precise.

> > BTW, is it normal that scheduled manual transactions gets applied automatically after the date of the transaction is passed?
> 
> When you observed this behaviour, was the manual plan still visible as a notification? Or was the phone switched up in the meantime?

Ah, nice point. The notification wasn't visible. It's possible that the device might have rebooted in the meantime. As I'm not sure, I wonder still about something. If I configure a monthly scheduled manual transaction for date X and that date passes without me applying the transaction, would that be automatically applied on day X+1 or would it still be left unapplied?

**Comment by mtotschnig** [comment]
In 3.1.3, the requested behaviour can be activated via Settings -> Advanced -> Planner
