### ISSUE TITLE
Old entries do not follow currency rates

### ISSUE THREAD

**Issue by WallGeckoPoint** [mtotschnig/MyExpenses#536]
I have a large set of accounts, some of them dating to before #362 was added. I have gone through and set the correct exchange rates on all of them, based on today's data. 

However, when I go to the home currency grand total account, it still shows the amounts from each account unconverted: so for example where an entry was for 100 INR, the payment shows as 100 EUR (in the home currency total account).

If I go to edit each individual payment, I can choose from the menu "equivalent amount" and it will pre-fill the correct quantity.

If I then save the payment, it shows up correctly in the home currency account (as 1.23 EUR).

However, this is not practical to do for every payment, since there are thousands of them!

How can I have every payment in an account use the account-wide exchange rate?

**Comment by mtotschnig** [comment]
Many thanks for the report, and my apologies for the late reaction. Normally every payment that has not set a specific equivalent amount should use the account-wide exchange rate. I examined if this actually works, and found that there is a bug where it does not work immediately after you change the home currency, but starts working once the app is restarted. I will fix this bug, and hope that the behaviour you describe was caused by it.
