### ISSUE TITLE
Charge date should auto-adjust to transaction date

### ISSUE THREAD

**Issue by woj-tek** [mtotschnig/MyExpenses#552]
This is a follow-up to #421

Simple use-case:
* make a transaction on day x
* enter the transaction on day 7 (let's say x + 10)
* by default both transaction date and charge date are on current time
* set `charge date' to date in the past 

Desired outcome - transaction time should be auto-adjusted to the 'charge date': this follows the logic as the transaction couldn't have happened after actual charge date and it would make entering older data easier.

**Comment by mtotschnig** [comment]
While reflecting about this, I was wondering how to "sell" this feature from an UX perspective. If the booking date would simple auto-adjust, this will be confusing for users at first, and they might suspect a bug. We could simply show a dialog the first time this auto-adjust takes place, but for some reason, users might also wish to deactivate it. So I was wondering if instead of silently auto-adjusting, it would work better if we would put a chain icon between the two buttons, that user could toggle between connected and broken state (Same as Gimp has in the canvas size dialog, where you link the width and height field, if you want to keep the aspect ratio). Then the adjustment would go in the two directions. @woj-tek What do you think?

**Comment by mtotschnig** [comment]
![image](https://user-images.githubusercontent.com/1485456/56092927-f050bc00-5ec2-11e9-8e86-f453f649ed10.png)

**Comment by woj-tek** [comment]
Hmm, this is not exactly the same because those dates doesn't have to be (always) linked. Quite often they may fall on the same day, but this is not 100% certain. What is certain, that if we adjust the charge date, then transaction day *has to* have the date at the latest of the charge (because bank can't charge you for transaction that hasn't happened yet).
What's more, most of the time this would only happen when adding past spending (for example something missed on particular day that showed up on the bank statement).

**Comment by mtotschnig** [comment]
I understand that it is not the same. Instead of automatically applying a logic (that you need to explain to the user), it provides a handle that allows the user to decide if the two dates should be updated in the same time.
I am not sure if the statement that "transaction day has to have the date at the latest of the charge" is necessarily sure for all users in all contexts. Sometimes users use the app in ways that do not comply with how things should behave by standard.
 In the same time, my solution allows for a use case which might also arise (although certainly not as frequently as yours): Entering future transactions, where you would also want the two dates to be identical.
