### ISSUE TITLE
Provide Nextcloud account integration

### ISSUE THREAD

**Issue by keunes** [mtotschnig/MyExpenses#682]
Hello,

Two commercial providers (Drive, Dropbox) are explicitly listed for synchronisation. Integration with Nextcloud for synchronisation is theoretically supported via WebDav, but many non-technical users may not know what it is or how to use it.

If they installed the Nextcloud app, an account is added on their phone. Would it be possible to offer 'Nextcloud' as an option and make use of this account listed on the phone? That way it's easy to add an account (without having to provide your password again).

([Keepass2Android](https://github.com/PhilippC/keepass2android/releases/tag/1.07) recently made Nextcloud integration explicit as well, hence the idea.)

**Comment by mtotschnig** [comment]
Improved NextCloud support would also include #1024 .

**Comment by mtotschnig** [comment]
This ticket being on top of the Roadmap Vote, I have started investigating the capacity of the Nextcloud app, and realized that it is integrated with Android's Storage Access Framework, which means that folders on Nextcloud can be treated more or less like local folders. This inspires the idea of creating a synchronization back-end that simply writes into a folder selected by the user. This could be a folder stored on Nextcloud, but also a local folder, that is synced to the network by other means, e.g. Syncthing.
But I am wondering if users voting for this issue are motivated because they want to make use of the synchronization mechanism in itself, or if they only need its secondary capacity of storing manual and automatic backups. Because for the later use case, you would not even need to setup a synchronization back-end. You could simply select a Nextcloud folder in My Expenses setting for backups and exports.

**Comment by keunes** [comment]
> This inspires the idea of creating a synchronization back-end that simply writes into a folder selected by the user.

I have no idea: isn't file synchronisation more prone to conflict errors than synchronisation via WebDav?

>  I am wondering if users voting for this issue are motivated because they want to make use of the synchronization mechanism in itself, or if they only need its secondary capacity of storing manual and automatic backups.

When creating the issue, I was mainly thinking of an automatic back-up solution. But I don't know of course what other voters had in mind.

Another thing to keep in mind I would say is forward compatibility: would either of the two approaches be more reliable in case a budgeting Nextcloud app [comes along](https://help.nextcloud.com/t/budget-app-any-interest/57788)?

**Comment by mtotschnig** [comment]
> I have no idea: isn't file synchronisation more prone to conflict errors than synchronisation via WebDav?

Good question. Theoretically there is a difference with respect to locking. The WebDav standard defines a locking mechanism that MyExpenses uses if it is available, but if I'm not mistaken, Nextcloud does not implement this part of the standard, so MyExpenses falls back to a file based locking approach, that would probably work the same in both cases. 
So the question probably is how Nextcloud's SAF implementation handles write operations in case of missing connectivity, or in case two devices write to the same file concurrently. If it would present to the client app on both devices a successful write even if the data is only written locally, then MyExpenses synchronization would break. I need to investigate that case.

**Comment by Popkornium18** [comment]
I have tried to set WebDav to sync and backup MyExpenses and it kinda worked but not in a satisfactory way. After some time the connection somehow failed and the sync backend was disabled. I voted for this, because I want to backup (and sync, but mostly backup) to Nextcloud in a reliable way that I don't have to futz around with every other day.

That said, I do keep seeing errors with apps that upload via Nextclouds file-sync, too. I'm not sure if they are actually errors I need to worry about though. The system backup baked into LineageOS (I believe it is [Seedvault](https://github.com/seedvault-app/seedvault)) uses Nextcloud and sometimes (maybe 1 in 100) an upload fails because the local file wasn't found. But maybe that's a Seedvault issue. However it doesn't require me to mess around with it to keep the backups going, which I appreciate a lot.

**Comment by mtotschnig** [comment]
@Popkornium18 Do you have a link to what Nextcloud's file-sync is? And can you give an example of an app that can be installed from F-Droid or Play that uses it?

**Comment by Popkornium18** [comment]
I just meant not using WebDav with manual server configuration but using the installed Nextcloud app to sync. I think it's what you meant by Nextclouds integration into Androids Storage Access Framework. They state that they use it [here](https://github.com/seedvault-app/seedvault/discussions/180).

**Comment by mtotschnig** [comment]
So the current situation is that for those interested only in storing automatic backups on Nextcloud, this is already possible without creating a WebDAV synchronization backend. You just have to use the option "Folder for backups and exports" in MyExpenses settings and then select a folder from Nextcloud via the systems file picker dialog (which uses the so-called SAF). There is a small gotcha that I am currently investigating that the backups are stored on Nextcloud without the zip extension, but backup restoration works.

**Comment by mtotschnig** [comment]
> I just meant not using WebDav with manual server configuration but using the installed Nextcloud app to sync. I think it's what you meant by Nextclouds integration into Androids Storage Access Framework. They state that they use it [here](https://github.com/seedvault-app/seedvault/discussions/180). Sorry for the confusing wording, I'm not an Android dev.

@Popkornium18 No problem. Thank you for the clarification.

**Comment by mtotschnig** [comment]
I would have liked to provide a NextCloud backend similar to the existing DropBox, Drive backends, and while there are NextCloud libraries that provide functionality for both the authorization part (https://github.com/nextcloud/Android-SingleSignOn) which allows to reuse the account created by the NextCloud client app and the File management part (https://github.com/nextcloud/android-library), unfortunately they do not work together [(](https://github.com/nextcloud/android-library/issues/232)). Which leaves 2 options:

1. Use Android-SingleSignOn and implement all the low-level WebDAV communication again.
2. Use android-library and prompt user for password.

At the moment, I am reluctant to go either way. I'll first experiment with the idea of creating a local file backend, that could be used to write into NextCloud via SAF.

**Comment by mtotschnig** [comment]
So 3.4.7 will come with a SAF backend, which allows to pick a folder from Nextcloud via Android's native file picker dialog if the Nextcloud app is installed.
I will leave this ticket open for a dedicated Nextcloud backend, but I'd like to ask all users who voted for this issue to give the SAF solution a try, and then either shift their vote to other issues, or comment here why the SAF approach does not work for them.

**Comment by mtotschnig** [comment]
Closing for the moment, please open again if the SAF approach does not work for you.
