### ISSUE TITLE
Roadmap Vote seems broken

### ISSUE THREAD

**Issue by primeapple** [mtotschnig/MyExpenses#708]
Hey,
idk if it is for me only, but the roadmap seems to not work correctly any more.
This page shows not all the issues with the roadmap_vote label : https://roadmap.myexpenses.mobi/issues.html

In the app itself 111 issues were found, but they all show 0 weight.

Is this for others, too?

**Comment by mtotschnig** [comment]
As announced [here](https://www.facebook.com/MyExpenses/posts/2768864520041675) I have reset the roadmap vote in order to get a fresh picture of current users' priorities. I have done this last time two years ago. One day after update to version 3.1.9 the app shows a dialogue inviting users to participate.

**Comment by mtotschnig** [comment]
The result page shows only issues for which users have voted.

**Comment by primeapple** [comment]
Alright, I didn't check facebook, so it is my bad then.
Is there a reason #667 doesn't appear in the list? You added the roadmap_voate label 5 days ago, what is the timeframe the application checks for newly labeled issues?

**Comment by mtotschnig** [comment]
I need to load the labeled issues via a script into the application, and forgot to do so. Sorry for the inconvenience! #667 should now appear in the app after you use the refresh command from the overflow menu.
