### ISSUE TITLE
Try to keep versionCode and Tags in sync

### ISSUE THREAD

**Issue by licaon-kter** [mtotschnig/MyExpenses#731]
...else F-Droid autoupdate will fail

Ref: https://gitlab.com/fdroid/fdroiddata/-/blob/e8d73dcc26564ceb0004ffe084adba7d9e26519c/metadata/org.totschnig.myexpenses.yml#L1505

Ref: https://github.com/mtotschnig/MyExpenses/blob/r450/myExpenses/build.gradle#L44

I'm fixing it now but for the future...

**Comment by mtotschnig** [comment]
Sorry for that, and thank you for fixing it. I will try to come up with a safer mechanism of creating the tags than manually from the shell.

**Comment by mtotschnig** [comment]
@licaon-kter I just realised that when in my answer to this problem, I extracted the versionCode to a variable (https://github.com/mtotschnig/MyExpenses/commit/3ab66d6898e240c86c71942bb166e035a9faafa1), I have broken the autoupdate's capability to extract the version code. Is there any means to get the autoupdate handle this kind of indirect definition of the version code? Otherwise I will revert back to expressing the versionCode directly for the next release, that is ready to be published.

**Comment by licaon-kter** [comment]
Yes via HTTP method, it greps a random (build.gradle in your case) file.

**Comment by mtotschnig** [comment]
@licaon-kter So how could I tell it to grep the root build.gradle instead of myExpenses/build.gradle ?

**Comment by mtotschnig** [comment]
@licaon-kter I only understood now that HTTP method referred to UpdateCheckMode. Unfortunately this would not work at the moment, since I am usually updating build.gradle before I consider the code base ready for publication. It is a pity that it is not possible to combine Tags and HTTP mode, so that the build would be triggered by a tag, but the information fetched via HTTP. For the moment, I have submitted a [PR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8399) for deactivating the auto updates. In the future, I will try to find a way to publish the version information so that it can be picked up by the HTTP method.

**Comment by licaon-kter** [comment]
:) https://gitlab.com/fdroid/fdroidserver/-/issues/768
