### ISSUE TITLE
Scheduled transactions on the 30th of the month are skipped in february

### ISSUE THREAD

**Issue by Popkornium18** [mtotschnig/MyExpenses#786]
I have scheduled two transactions on the 30th day of the month which were both skipped in february.
I know it kinda makes sense when you think about it and also that I just could schedule them on the first of the month and be done with it, but it is also a little bit counterintuitive. 
I think it would be beneficial if the last day of the month would be used instead of just skipping it.

**Comment by mtotschnig** [comment]
As mentioned [here](https://github.com/mtotschnig/MyExpenses/issues/453#issuecomment-789490164), My Expenses at the moment, depends on the capability of the calendar app to support recurring dates on the last day of the month. But since the standard Calendar app, doesn't support it, I'll try to implement it, inside the app shortly.

**Comment by mtotschnig** [comment]
Unfortunately, the ICAL processor on Android does not correctly handle an event that should occur on every 30th as described here: https://issuetracker.google.com/issues/183019130

**Comment by mtotschnig** [comment]
As a consequence I will add only the option for setting a recurrence for the last day of each month.
