### ISSUE TITLE
"Save and New" feature no longer works when adding Split parts

### ISSUE THREAD

**Issue by dalaeance** [mtotschnig/MyExpenses#790]
I used to be able to add parts of Split transactions in rapid succession, but now I need to back out and add each one individually, along with the category & description (we always had to add the amount manually when doing "save and new" with parts, so no loss there).

I know the app was recently updated via F-Droid.

**Comment by mtotschnig** [comment]
@dalaeance  Do you remember in which version you were able to do that? As far as I know, the app was until now trying to configure the "Save and New" feature only for main transactions. There might have been a version where it accidentally also worked for split parts.
That said, you are right that it could also be supported for split parts.

**Comment by dalaeance** [comment]
I'm fairly certain I was able to do it up to the most recent version or secondmost-recent (3.2.4.2 or 3.2.4.1). I've been using splits like that for a long time now. Likely over a year. I'm 95% certain I used it up until March 12 because that was my last split transaction, and it was a sizeable one.

**Comment by dalaeance** [comment]
Did some testing on a spare phone and I've confirmed that "Save and New" worked on split transactions up to, and including, version 3.2.4.2.

**Comment by mtotschnig** [comment]
In my tests, "Save and New" only works for split parts in 3.2.4.2 if you start from editing an existing split part. From a new split part, it does not work.
Anyway, I will add it now, officially supported, to split parts.

**Comment by dalaeance** [comment]
Yeah, that's how it's worked all this time I've been using it. I assumed it was done this way on purpose. Haha. It worked well enough that I didn't think to ask for it to also work with new split parts.

Thanks for adding official support. (:

**Comment by mtotschnig** [comment]
As you may have noticed, the state of the "Save and New" toggle button in the menu is persisted to preferences. So that once it is set, when you create a new transaction, it will be active. My idea is to have two distinct preferences for main transactions and split parts, so that you could have it on by default only for split parts or only for main transactions. @dalaeance What do you think?

**Comment by mtotschnig** [comment]
And in the future it will only work when you start from a new part in order to mimic the behaviour for main transactions. Or is there any reason you would need it to work also when you edit an existing split part?

**Comment by dalaeance** [comment]
I like that idea. Though, I'd also like to have the option for "Save and New" to be applicable to both at the same time. So there'd be 3 possibilities:
- applicable to main transactions only
- applicable to split parts only
- applicable to both, kind of like how it's worked until recently 

I think that, in the vast majority of cases, it'll only need to be applicable to new split parts. However, there are times when I'll save a split part containing the remaining amount to be split, with the intention of coming back and splitting it up later. So I think also being able to edit an existing split part would be great. You could add an extra toggle that's off by default, for editing existing split parts, if you think it'll keep things simpler for people without this use case.

**Comment by mtotschnig** [comment]
For the moment, I would stick with the behaviour of Save and new only being available after creating a new object. The reason is that I want the handling of parts and parents to be consistent. And I think that generally, it is more intuitive that when you edit an existing item, there is no "Save and new" button.
Maybe it is acceptable for you in your described use case, that when you edit an existing split part, after having edited it, you need to click on new part and then have Save and new working. If not, please open a new issue.

**Comment by dalaeance** [comment]
I think that could work. I'll def try to work with it, and report back if I find it doesn't work, but I don't anticipate it being a significant issue.
