### ISSUE TITLE
Editing initial value of a synchronized account duplicates it

### ISSUE THREAD

**Issue by jlnbdt** [mtotschnig/MyExpenses#864]
Hi,

I've edited the initial value of a synchronized account. This operation seems to duplicate it: a new folder appears in my Nextcloud folder where the sync is set, and this account appears twice when I list all accounts on the dedicated page in MyExpenses.

Is it safe to delete the "old" directory related to this account in Nextcloud folder?

**Comment by mtotschnig** [comment]
I tried to reproduce the problem, but was not able to. When an account that is synced is edited, normally the metadata.json file should be changed, and an additional changes file created in the folder.
I suspect that the problem you describe might be caused by something else. Normally folders have the uuid of the account as names? How are the two folders named in your case? If they have different uuids, the second folder might be related to some other account that you have tried to sync?

**Comment by mtotschnig** [comment]
I am not sure why it did not reproduce when I last checked, but I can now clearly see this happen. The problem is unfortunately more serious, in most cases it probably breaks the existing synchronization, and cannot be repaired without starting the synchronization again.
