### ISSUE TITLE
New search Parameter 

### ISSUE THREAD

**Issue by amarradi** [mtotschnig/MyExpenses#894]
Is there a possibility to introduce new search parameters?
-All bookings made from templates 
-All entries separated by income and expenses

**Comment by mtotschnig** [comment]
I understand the utility of the first point, but it would probably only work for plans. Because we only store links between transactions to plans, i.e. to the specific instance date of the plan.
I am not sure, I understand the second point. Do you mean that you only want to see either income or expenses. This is already possible with the amount filter.
