### ISSUE TITLE
[Bug] Debt Overview showing incorrect message if the starting amount is 0

### ISSUE THREAD

**Issue by jackblk** [mtotschnig/MyExpenses#905]
How to reproduce:

* Create a party (ABC for example)
* Create a debt via New debt
* In Amount, leave empty or input 0 -> the message is now `I owe ABC $0`. I expect to see no message here, or message like "Even, no debt".
* Create a transaction from your wallet to that party (this is the transaction where I lend the party the money), for example $100 -> total amount is now $100

Expected: in Debt Overview, it displays: `ABC owes me $100` with a green text (indicating that ABC owes me).

Observed: in Debt Overview, it displays: `I owe ABC $100` with a green text (indicating that ABC should owe me).

---

My suggestion: the message should follow the plus/minus sign (+/-) if the starting amount is 0. If I put the starting amount as `-0` (red button) then I owe the party. If I put it as `+0` (green button) then the party owes me.

**Comment by mtotschnig** [comment]
I will change the implementation of the debt overview, so that the current balance of the debt determines if "I owe X" or "X owes me" is displayed. If the balance is 0, only the name of the party is displayed.
I prefer to not touch the implementation of the debt edit screen for the moment, because I would like the switch to immediately indicate that it determines the direction of the debt, even if the amount is still 0.

**Comment by jackblk** [comment]
Awesome, it looks great now, thanks!
