### ISSUE TITLE
UX for category selection

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#961]
Previously: Clicking on a main category toggled expansion state. In order to select a main category, you had to long tap to order context menu.
Now: Clicking on a main category selects it.

Users might prefer the old behavior, because they never directly select categories, that have children, but always use terminal categories.

We should allow user to choose between these two behaviours.

**Comment by alexandrpaliy** [comment]
Just my personal experience, but

> they never directly select categories, that have children

not true :) at least, not all of them

> Now: Clicking on a main category selects it.

I was very happy today, using new UI, because I could easily select parent category with only one tap instead of "long press, then click the mark button".

Of course, I use child categories most of the time, but they are still easily accessible if you tap on "unfold buttons" instead of the names of parent categories.


> We should allow user to choose between these two behaviours.

I'm absolutely fine with that idea, and I'll be fine even if you make "old experience" as a default one. I just ask you to not remove the "new experience" at all.

**Comment by mtotschnig** [comment]
@alexandrpaliy Thank you very much for the feedback.

> Users might prefer the old behavior, because they never directly select categories, that have children, but always use terminal categories.

I actually meant that those users, who never directly select categories with children, will prefer the old behavior. Not that all users only use terminal categories.

**Comment by mtotschnig** [comment]
In 3.3.8.1, the old behaviour (tap -> expand / collapse) is now default again. Tap -> selects can be configured from the overflow menu: https://mastodon.social/web/@myexpenses/108187423818394702
